"use client";
import Navbar from "@/components/admin/layout/Navbar";
import Link from "next/link";

import { Inter } from "next/font/google";
import NoSSRToaster from "@/components/NoSSRToaster";
import { EtherSignerContext } from "@/context/EtherSignerContext";
import { useState } from "react";
import Footer from "@/components/admin/layout/Footer";
import { EtherProviderContext } from "@/context/EtherProviderContext";
import { ethers } from "ethers";
import ElectionStages from "@/components/admin/layout/ElectionStages";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  const [signer, setSigner] = useState("");
  const signerObject = { signer, setSigner };

  return (
    <>
      <NoSSRToaster></NoSSRToaster>

      <EtherSignerContext.Provider value={signerObject}>
        <EtherProviderContext.Provider
          value={
            window.ethereum == null
              ? null
              : new ethers.BrowserProvider(window.ethereum)
          }
        >
          <Navbar />
          <div style={{ height: "72vh" }}>
            <ElectionStages>{children}</ElectionStages>
          </div>

          <Footer></Footer>
        </EtherProviderContext.Provider>
      </EtherSignerContext.Provider>
    </>
  );
}
